#!/bin/bash

####################################################
# CREATION     : 2016-05-26
# MODIFICATION : 2016-07-20

# I3block's blocklet which:
# - Display current state & played song in cmus
# - Control cmus via the mouse (m/l/r <=> pause/next/previous)
# - Move in the track (wheel up/down)
####################################################

getCmus() {
	if [ ! -x "/usr/bin/cmus" ]
	then
		echo ""
		return 1
	fi

	status=$(cmus-remote -Q | grep "status " | cut -d " " -f 2)
	artist=$(cmus-remote -Q | grep "^tag artist " | sed -e "s/^tag artist //")
	title=$(cmus-remote -Q | grep "^tag title " | sed -e "s/^tag title //")

	if [ -z "$status" ]
	then
		echo ""
		return 1
	fi

	case $status in
		"playing" )
			icon="";;
		"paused" )
			icon="";;
		"stopped" )
			icon="";;
	esac

	if [ -z "$artist" ] && [ -z "$title" ]
	then
		echo "$icon"
	else
		echo "$icon ${artist} - ${title}"
	fi
}

goto_track="cmus-remote -C win-sel-cur"
case $BLOCK_BUTTON in
    1) cmus-remote --next && $goto_track;;     # left click
    2) cmus-remote --pause && $goto_track;;    # middle click
    3) cmus-remote --prev && $goto_track;;     # right click
    4) cmus-remote --seek +10;;  # wheel up
    5) cmus-remote --seek -10;;  # wheel down
esac

cmus=$(getCmus)
if [ -z "$cmus" ]
then
	echo ""
	echo ""
else
	echo $cmus
	echo $cmus
	echo "#f6f6f6"
fi
echo
