if [ -f ~/.bashrc ]; then
	source ~/.bashrc
fi

# For spinning bug in DreamChess.
export SDL_JOYSTICK_DEVICE=/dev/null

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" 