# #############################
# Last modification: 2014-09-03
# #############################

# Pour Git
alias Gcl="git clone"
alias Gi="git init"
alias Gl="git log"
alias Gb="git branch"
alias Gch="git checkout"
alias Gpl="git pull"
alias Ga="git add"
alias Gs="git status"
alias Gco="git commit"
alias Gd="git diff"
alias Gm="git merge"
alias Gp="git push -u origin "

# Pour 'apt'
alias Upd='sudo apt update'
alias Upg='sudo apt upgrade'
alias Ins='sudo apt install'
alias Del='sudo apt --purge remove'
alias AddRepo='sudo add-apt-repository'
alias DelRepo='sudo add-apt-repository --remove'
alias Ar='sudo apt-get autoremove'
alias Ac='sudo apt-get autoclean'
alias Search='apt search $1'
alias List='apt list -a $1'
alias Show='apt show $1'

# Extraction & compression des archives tar et bzip2.
alias ETarG='tar -zxvf $1' # Extraire Gzip.
alias CTarG='tar -zcvf $1' # Compresser dans un Gzip.
alias ETarB='tar -jxvf $1' # Extraire Bzip2.
alias CTarB='tar -jcvf $1' # Compresser dans un Bzip2.

# Pour XAMPP/LAMPP
alias XOn='sudo /opt/lampp/lampp start'
alias XOff='sudo /opt/lampp/lampp stop'

# Dossiers spéciaux.
alias www='cd /opt/lampp/htdocs/mesProjets/'
alias ww='cd /opt/lampp/htdocs/mesProjets/ && cd $1'

# Pour "InitWebProject"
alias ISWP='. InitWebProject.sh '

# Pour 'dpkg'
alias DIns='sudo dpkg -i $1'
# alias List='dpkg -l | grep -i '

# Pout 'tmux'
alias tmux='tmux -2'
alias TmL='tmux ls'
alias TmK='tmux kill-session -t $1'

# Pour 'avconv'
alias AVC1366='avconv -f x11grab -s wxga -r 25 -i :0.0 ~/Vidéos/tuto.mp4'
alias AVC720='avconv -f x11grab -s hd720 -r 25 -follow_mouse 50 -i :0.0 ~/Vidéos/tuto.mp4'

# Pour 'ps'
alias PsN='ps -o pid,comm,pcpu,rss,stat,etime,args -C ' # Par rapport au nom du processus.
alias PsP='ps -o pid,comm,pcpu,rss,stat,etime,args -p ' # Par rapport au PID du processus.
alias PsS='ps -ef | grep -i '

# Remettre l'icône monochrome de CherryTree dans le panel
alias Cherry='sudo cp -v ~/.icons/CherryTree/* /usr/share/cherrytree/glade/'

# Pour 'ls'
alias LsD='ls -F | grep "/$"'		   # Ne lister que les répértoires.
alias LsF='ls -F | grep -e ".*[^\/]$"' # Ne lister que les fichiers..
alias LsH='ls -A | grep "^\."'		   # Ne lister que les fichiers cachés.

# Divers
alias V='vim'
alias G='gvim'
alias Size='df -h'
alias RelB='source ~/.bashrc'
