if [ -f ~/.profile ]; then
	source ~/.profile
fi

if [ -f ~/.bashrc ]; then
	source ~/.bashrc
fi

# For spinning bug in DreamChess.
export SDL_JOYSTICK_DEVICE=/dev/null

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" 

# Use keychain for ssh it its installed & only in i3
if [ -x "/usr/bin/keychain" ] && [ "$DESKTOP_SESSION" == "i3" ]; then
	eval `keychain --eval --quiet --agents ssh id_rsa`
fi

# vim:ft=sh
