# #############################
# Last modification: 2016-09-28
# #############################

# Git
alias Gtree="git log --graph --decorate --pretty=oneline --abbrev-commit"

# Apt & dpkg
alias Upd='sudo apt update'
alias Upg='sudo apt upgrade'
alias Ins='sudo apt install'
alias Del='sudo apt --purge remove'
alias AddRepo='sudo add-apt-repository'
alias DelRepo='sudo add-apt-repository --remove'
alias Ar='sudo apt-get autoremove'
alias Ac='sudo apt-get autoclean'
alias Search='apt search'
alias List='apt list -a'
alias Show='apt show'
alias DIns='sudo dpkg -i'

# Gzip & bzip2 extraction & compression des archives tar et bzip2.
alias ETarG='tar -zxvf' # Extract Gzip.
alias CTarG='tar -zcvf' # Compress in a Gzip.
alias ETarB='tar -jxvf' # Extract Bzip2.
alias CTarB='tar -jcvf' # Compress in a Bzip2.

# Tmux
alias tmux='tmux -2'
alias TmL='tmux ls'
alias TmK='tmux kill-session -t '

# Avconv
alias AVC1366='avconv -f x11grab -s wxga -r 25 -i :0.0 ~/Vidéos/tuto.mp4'
alias AVC720='avconv -f x11grab -s hd720 -r 25 -follow_mouse 50 -i :0.0 ~/Vidéos/tuto.mp4'

# Ps
alias PsN='ps -o pid,comm,pcpu,rss,stat,etime,args -C ' # By name
alias PsP='ps -o pid,comm,pcpu,rss,stat,etime,args -p ' # By PID
alias PsS='ps -ef | grep -i '

# Remettre l'icône monochrome de CherryTree dans le panel
# alias IcnCherry='sudo cp -v ~/.icons/CherryTree/* /usr/share/cherrytree/glade/'
# alias IcnKeePassx='sudo cp -v ~/.icons/KeePassX/keepass*[^OLD].png /usr/share/keepassx/icons/'
# alias IcnXfceNote='sudo cp -v ~/.icons/Xfce4-notes-panel/xfce4-notes-plugin.png /usr/share/icons/Faenza-Dark/status/22/'
# alias IcnPidgin='sudo cp -v ~/.icons/Pidgin-tray/* /usr/share/icons/Faenza-Dark/status/22/'
# alias IcnTurpial='cp -v ~/.icons/Turpial/turpial_icon.png /home/k-bag/Scripts/turpial/turpial/data/pixmaps/turpial-tray.png'

# Ls
alias LsD='ls -F | grep "/$"'		   # Only directories
alias LsF='ls -F | grep -e ".*[^\/]$"' # Only files
alias LsH='ls -A | grep "^\."'		   # Only hidden files
alias ll='ls -l'

# Misc
alias Do='python3 "$HOME/.dotfiles/scripts/do.py"'
alias lyvi='python3 "$HOME/Scripts/lyvi/lyvi.py"'
alias V='vim'
alias G='gvim'
alias Size='df -h'
alias RelB='exec bash'
alias Watch='watch -t --differences '
alias Weather='curl wttr.in/novoazovsk'
# Vim & gvim vanilla
alias Vv='vim -Nu ~/.vimVanilla/vimrc'
alias Gv='gvim -Nu ~/.vimVanilla/vimrc'

# vim:ft=sh
